## Game Boy and Game Boy Color for MEGA65 (gbc4mega65)
##
## Core specific constraints
##
## This machine is based on Gameboy_MiSTer
## Powered by MiSTer2MEGA65
## MEGA65 port done by sy2002 in 2021 - 2026 and licensed under GPL v3


## Name Autogenerated Clocks
##
## main_clk is the Game Boy machine clock (8 x 4.194304 MHz = 33.554432 MHz); gb.v derives
## CE-gated clocks from it (clk_sys & ce), which Vivado times automatically as main_clk.
## Note that speedcontrol.vhd and parts of gb.v use the falling edge - both edges of
## main_clk are therefore timed automatically.
## video_clk is the lcd.v video clock (16 x 4.194304 MHz = 67.108864 MHz, exactly 2x
## main_clk from the same MMCM, so main_clk<->video_clk paths are timed as related clocks).
##
## HDMI flicker-free: clk.vhd generates two clock legs - "native" (i_clk_main, 59.73 Hz
## frame rate) and the flicker-free "fast" twin (i_clk_fast, 60.05 Hz) - and two
## BUFGMUX_CTRL select between them from hr_core_speed(0) (the FSM in mega65.vhd). We time
## the SHORTEST-period leg for worst-case setup: set_case_analysis 1 freezes the select on
## the fast leg, and main_clk/video_clk are defined on i_clk_fast's outputs. Those two
## generated clocks constant-propagate the native leg off the net, so no set_clock_groups
## is needed (the C64MEGA65/AExp pattern).
##
## PIN-NAME DISCIPLINE (load-bearing): if either get_pins matches nothing (instance
## renamed, or the select FF merged/retimed away), Vivado only WARNS ("no pins matched")
## and the constraint silently no-ops - an empty set_case_analysis re-introduces phantom
## native<->fast inter-clock paths, and main_clk/video_clk become undefined. Keep the leaf
## names i_clk_fast (clk.vhd) and hr_core_speed (mega65.vhd). Post-synth sign-off gate:
## all get_pins must return non-empty, and the routed report must show main_clk at
## ~29.644 ns and video_clk at ~14.822 ns (the fast periods).
set_case_analysis 1 [get_pins CORE/hr_core_speed_reg[0]/Q]
create_generated_clock -name video_clk [get_pins CORE/clk_gen/i_clk_fast/CLKOUT0]
create_generated_clock -name main_clk  [get_pins CORE/clk_gen/i_clk_fast/CLKOUT1]
# Add more clocks here, if needed

## ascal asynchronous FIFO data crossings (framework paths, constrained here
## because M2M/common.xdc must not be modified - candidate for upstreaming;
## the same constraints are used by the AExp core).
##
## ascal's input and output double buffers (i_dpram/o_dpram, explicitly kept
## in LUTRAM with ram_style="distributed") are ping-pong CDC FIFOs: i_dpram
## is written on i_clk (= video_clk) and read on avl_clk (= hr_clk); o_dpram is
## written on avl_clk and read on o_clk (= hdmi_clk). The handshake registers
## are already cut by the false_path patterns in M2M/common.xdc, but
## those match only register /C pins. The LUTRAM primitives launch from their
## /CLK pins and would otherwise be timed at the worst-case edge alignment of
## unrelated MMCM outputs.
##
## set_max_delay -datapath_only bounds the data staleness to one destination
## clock period and removes the hold analysis.
set_max_delay -datapath_only 10.000 \
   -from [get_pins -hierarchical -regexp {.*/i_ascal/i_dpram_reg.*/CLK}] \
   -to   [get_cells -hierarchical -regexp {.*/i_ascal/avl_dr_reg\[[0-9]+\]}]
set_max_delay -datapath_only 13.400 \
   -from [get_pins -hierarchical -regexp {.*/i_ascal/o_dpram_reg.*/CLK}] \
   -to   [get_cells -hierarchical -regexp {.*/i_ascal/o_dr_reg\[[0-9]+\]}]
