## Game Boy Color for MEGA65 (gbc4mega65)
##
## Core specific constraints
##
## This machine is based on Gameboy_MiSTer
## Powered by MiSTer2MEGA65
## MEGA65 port done by sy2002 & MJoergen in 2021, 2024 and licensed under GPL v3

## Autogenerated Clocks
create_generated_clock -name video_clk     [get_pins CORE/clk_gen/i_clk_main/CLKOUT0]
create_generated_clock -name main_clk      [get_pins CORE/clk_gen/i_clk_main/CLKOUT1]
