; DO NOT MANUALLY EDIT
; AUTOGENERATED BY ./make_rom.sh
; These constants are equal to the menu indexes defined in
; ../vhdl/mega65.vhd and in ../vhdl/config.vhd

; -----------------------------------------------------------------
; gbc4mega65 specific OSM item constants
; -----------------------------------------------------------------

GBC_OSM_GB_CLASSIC              .EQU 6
GBC_OSM_GB_COLOR                .EQU 7
GBC_OSM_COL_SATURATED           .EQU 11
GBC_OSM_COL_LCDEMU              .EQU 12
GBC_OSM_JOY_STD_A               .EQU 17
GBC_OSM_JOY_STD_B               .EQU 18
GBC_OSM_JOY_UP_A                .EQU 19
GBC_OSM_JOY_UP_B                .EQU 20
GBC_OSM_HDMI_720P_60            .EQU 26
GBC_OSM_HDMI_640_60             .EQU 27
GBC_OSM_HDMI_480_5994           .EQU 28
GBC_OSM_HDMI_800_60             .EQU 29
GBC_OSM_HDMI_FF                 .EQU 31
GBC_OSM_HDMI_ZOOM               .EQU 32
GBC_OSM_HDMI_FLT_NO_FILTER      .EQU 38
GBC_OSM_HDMI_FLT_SHARP          .EQU 39
GBC_OSM_HDMI_FLT_BICUBIC        .EQU 40
GBC_OSM_HDMI_FLT_SMOOTH         .EQU 41
GBC_OSM_HDMI_FLT_LANCZOS        .EQU 42
GBC_OSM_HDMI_FLT_SCANLINES      .EQU 43
GBC_OSM_HDMI_FLT_CRT_SVIDEO     .EQU 44
GBC_OSM_HDMI_FLT_CRT_COMPOSITE  .EQU 45
GBC_OSM_VGA_STD                 .EQU 51
GBC_OSM_VGA_15KHZHSVS           .EQU 55
GBC_OSM_VGA_15KHZCS             .EQU 56
GBC_OSM_IMPROVE_AUDIO           .EQU 59

; -----------------------------------------------------------------
; gbc4mega65 specific menu group items
; -----------------------------------------------------------------

GBC_OPTM_G_CART                 .EQU 1
GBC_OPTM_G_GBMODE               .EQU 2
GBC_OPTM_G_COLMODE              .EQU 3
GBC_OPTM_G_JOYMODE              .EQU 4
GBC_OPTM_G_HDMI                 .EQU 5
GBC_OPTM_G_HDMI_FF              .EQU 6
GBC_OPTM_G_HDMI_ZOOM            .EQU 7
GBC_OPTM_G_HDMI_FLT             .EQU 8
GBC_OPTM_G_VGA                  .EQU 9
GBC_OPTM_G_AUDIO                .EQU 10
GBC_OPTM_G_ABOUT                .EQU 11

; -----------------------------------------------------------------
; gbc4mega65 specific QNICE device ids
; -----------------------------------------------------------------

GBC_DEV_CART                    .EQU 0x0100
GBC_DEV_BIOS                    .EQU 0x0101
